//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageNineTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageNineTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;feed xmlns=&apos;http://www.w3.org/2005/Atom&apos; xmlns:gphoto=&apos;http://schemas.google.com/photos/2007&apos; xmlns:media=&apos;http://search.yahoo.com/mrss/&apos; xmlns:openSearch=&apos;http://a9.com/-/spec/opensearchrss/1.0/&apos;&gt;
        ///  &lt;id&gt;http://picasaweb.google.com/data/feed/api/user/robertov82%40gmail.com&lt;/id&gt;
        ///  &lt;updated&gt;2010-09-08T19:48:09.362Z&lt;/updated&gt;
        ///  &lt;category scheme=&apos;http://schemas.google.com/g/2005#kind&apos; term=&apos;http://schemas.google.com/photos/2007#user&apos;/&gt;
        ///  &lt;title type=&apos;text&apos;&gt;robertov82 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AlbumFeed {
            get {
                return ResourceManager.GetString("AlbumFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;feed xmlns=&apos;http://www.w3.org/2005/Atom&apos; xmlns:exif=&apos;http://schemas.google.com/photos/exif/2007&apos; xmlns:gphoto=&apos;http://schemas.google.com/photos/2007&apos; xmlns:media=&apos;http://search.yahoo.com/mrss/&apos; xmlns:openSearch=&apos;http://a9.com/-/spec/opensearchrss/1.0/&apos; xmlns:gml=&apos;http://www.opengis.net/gml&apos; xmlns:georss=&apos;http://www.georss.org/georss&apos;&gt;
        ///  &lt;id&gt;https://picasaweb.google.com/data/feed/api/user/robertov82/albumid/5490824849223202081&lt;/id&gt;
        ///  &lt;updated&gt;2010-07-07T11:55:37.269 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PhotosFeed {
            get {
                return ResourceManager.GetString("PhotosFeed", resourceCulture);
            }
        }
    }
}
